# -*- coding: utf-8 -*-
"""Data_Analysis_Project1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/Keerthi-Busana/Keerthi-Busana/blob/main/Data_Analysis_Project1.ipynb
"""

import numpy as np
import pandas as pd

carloans = [[1, 323344.5, 3334, 555, 445, 656, 734, 0.702, 'Toyota Sienna'],
           [2, 545665,  56567, 434, 454, 455, 565, 0.702,  'Toyota Sienna'], 
            [3, 3233.5, 3434, 5455, 4455, 6546, 7534, 0.702, 'Toyota Sienna'],
            [4, 545665,  56567, 434, 454, 455, 465, 0.702,  'Toyota Sienna']]

colnames = ['Month',
            'Starting Balance',
            'Repayment',
            'Interest Paid',
            'Principal Paid',
            'New Balance',
            'term',
           'interest_rate',
            'car_type']

df = pd.DataFrame(data = carloans, columns = colnames)

df

filename = ("/content/car_financing.csv")
df = pd.read_csv(filename)

df

#top N records 

df.head()

#bottom N records

df.tail()

#check column datatypes

df.dtypes

#to find the number of rows and columns

df.shape

#info method tells how many non-null values are there + data types

df.info()

# to select only one column of a dataset

df[['car_type']].head()

df[['car_type', 'Month']].head()

type(df[['car_type']].head())

df[['car_type']][0:10]

"""## **Data Filtering Process**

"""

#Counting different car types

df['car_type'].value_counts()



"""The above output has spelling mistake. Instead of 'Corolla', it is written as ' Carolla'

> Indented block


"""

#the filter procduces a pandas series of True and False values # We just want to choose Toyota Sienna cars

car_filter = df['car_type'] == 'Toyota Sienna'

car_filter.head()

df[car_filter].head() # Cheacking the top values

df.loc[car_filter, :] # checking all values if they all have Toyota Sienna cars

df['car_type'].value_counts() #The values did not change because we did not add filter data frame to the original data frame

df = df.loc[car_filter, :] # filter dataframe to get a DataFrame of only 'Toyota Sienna

df['car_type'].value_counts() # Now instead of having all values, we just have values with Toyota Sienna

#Interest_rate Filter

df['interest_rate'].value_counts()

df['interest_rate'] == 0.0702 #this produces the True and False values. The True values are with 0.0702 and the False one are 
                                                           # of 0.359 values

interest_filter = df['interest_rate']== 0.0702

df = df.loc [interest_filter, :] # loc is lock attribute

df['interest_rate'].value_counts(dropna= False)

df.loc[car_filter & interest_filter, : ] #to combine everything

"""Renaming and Removing columns: 

1. Renaming Columns:
Dictionary Substitution
List Replacement



"""

